services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/media:/app/media
    env_file:
      - .env
    depends_on:
      - frontend
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db_data: