version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - frontend
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./dist:/app/dist
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db_data: