# Generated by Django 4.2 on 2025-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20250411_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembling', 'Собирается'), ('delivering', 'Доставляется'), ('completed', 'Завершён')], db_index=True, default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
