# Generated by Django 4.2 on 2025-04-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан, готовящий заказ'),
        ),
    ]
